### ISSUE TITLE
TypeError: Odd-length string

### ISSUE THREAD

**Issue by soiax** [GoSecure/break-fast-serial#1]
> Exception happened during processing of request from ('*********', 50707)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
>     self.handle()
>   File "dnschef.py", line 332, in handle
>     response = self.parse(data)
>   File "dnschef.py", line 95, in parse
>     qname_handler(qname)
>   File "~/break-fast-serial/dnschef/exfilchef.py", line 8, in qname_handler
>     data = unhexlify(subdomain)
> TypeError: Odd-length string
> 

I guess unhexlify gets a string with spaces, that's when this error occurs according to google :P

I just tested the thing, it worked fine with host,wget... this happened when i tried the domain from browsers.

**Comment by h3xstream** [comment]
Yup. Any subdomain that is not in hex will likely crash dnschef.

**Comment by h3xstream** [comment]
It should be fix. Nothing will be logged if the length of the sub-domain is odd.
